In [31]:
import numpy as np
import numpy.linalg as la
np.set_printoptions(edgeitems=10,linewidth=180)

In [5]:
A = np.random.normal(size=(5, 3))

In [10]:
b = np.random.normal(size=(3, 1))

In [13]:
x = A @ b

In [17]:
y = x + np.random.normal(size=(5, 1)) * 0.1

In [25]:
la.solve(A.T @ A, A.T @ y)

array([[ 1.46095225],
       [-0.62246249],
       [ 0.48663837]])

In [46]:
(A @ la.inv(A.T @ A)).T

array([[-0.23960172, -0.27654616,  0.04297668,  0.27697355,  0.09140135],
       [ 0.06303891, -0.11701286, -0.2526327 , -0.24197649,  0.18668461],
       [ 0.1965595 ,  0.24615895,  0.17291884, -0.50286756,  0.4247457 ]])

In [44]:
la.pinv(A)

array([[-0.23960172, -0.27654616,  0.04297668,  0.27697355,  0.09140135],
       [ 0.06303891, -0.11701286, -0.2526327 , -0.24197649,  0.18668461],
       [ 0.1965595 ,  0.24615895,  0.17291884, -0.50286756,  0.4247457 ]])

In [47]:
Mmag = np.array(
    [[1, 1, 0, 0, 0, 1, 0, 0],     # baseline type 1 (4 rows)
     [0, 1, 1, 0, 0, 1, 0, 0],
     [0, 0, 1, 1, 0, 1, 0, 0],
     [0, 0, 0, 1, 1, 1, 0, 0],
     [1, 0, 1, 0, 0, 0, 1, 0],     # baseline type 2 (3 rows)
     [0, 1, 0, 1, 0, 0, 1, 0],
     [0, 0, 1, 0, 1, 0, 1, 0],
     [1, 0, 0, 1, 0, 0, 0, 1],     # baseline type 3 (1 row)
     [0, 1, 0, 0, 1, 0, 0, 1],
     [1, 0, 0, 0, 0, 0, 0, 0]])    # magnitude constriant

In [49]:
Mmag.T @ Mmag

array([[4, 1, 1, 1, 0, 1, 1, 1],
       [1, 4, 1, 1, 1, 2, 1, 1],
       [1, 1, 4, 1, 1, 2, 2, 0],
       [1, 1, 1, 4, 1, 2, 1, 1],
       [0, 1, 1, 1, 3, 1, 1, 1],
       [1, 2, 2, 2, 1, 4, 0, 0],
       [1, 1, 2, 1, 1, 0, 3, 0],
       [1, 1, 0, 1, 1, 0, 0, 2]])

In [50]:
la.qr(Mmag)

(array([[-5.00000000e-01, -3.87298335e-01,  2.10818511e-01,  1.78174161e-01,  3.05566166e-02,  4.71404521e-01, -2.74288043e-01, -2.42390176e-01],
        [-0.00000000e+00, -5.16397779e-01, -4.21637021e-01,  1.78174161e-01,  2.44452933e-01,  2.35702260e-01,  2.53716440e-01,  1.03881504e-01],
        [-0.00000000e+00, -0.00000000e+00, -5.27046277e-01, -4.45435403e-01,  2.44452933e-01,  2.35702260e-01,  2.53716440e-01,  1.03881504e-01],
        [-0.00000000e+00, -0.00000000e+00,  0.00000000e+00, -5.34522484e-01, -5.19462482e-01,  4.71404521e-01, -2.33144837e-01,  3.46271681e-02],
        [-5.00000000e-01,  1.29099445e-01, -4.21637021e-01,  1.78174161e-01,  3.05566166e-02, -2.35702260e-01, -2.74288043e-01, -2.42390176e-01],
        [-0.00000000e+00, -5.16397779e-01,  1.05409255e-01, -4.45435403e-01,  2.44452933e-01, -4.71404521e-01, -4.45718070e-01,  2.07763008e-01],
        [-0.00000000e+00, -0.00000000e+00, -5.27046277e-01,  8.90870806e-02, -5.19462482e-01, -2.35702260e-01, -2.33144837e-