In [2]:
import numpy as np
import numpy.linalg as la
np.set_printoptions(edgeitems=10,linewidth=180)

In [3]:
A = np.random.normal(size=(5, 3))

In [4]:
b = np.random.normal(size=(3, 1))

In [5]:
x = A @ b

In [6]:
y = x + np.random.normal(size=(5, 1)) * 0.1

In [7]:
la.solve(A.T @ A, A.T @ y)

array([[-0.67505608],
       [-2.86043278],
       [-0.71143959]])

In [8]:
(A @ la.inv(A.T @ A)).T

array([[-0.25598533,  0.03824366, -0.06819445,  0.07011201,  0.18594547],
       [ 0.04935921,  0.34310073,  0.16015002,  0.32968007, -0.16893236],
       [-0.14501155, -0.12274237, -0.3559236 , -0.32723973,  0.00540127]])

In [9]:
la.pinv(A)

array([[-0.25598533,  0.03824366, -0.06819445,  0.07011201,  0.18594547],
       [ 0.04935921,  0.34310073,  0.16015002,  0.32968007, -0.16893236],
       [-0.14501155, -0.12274237, -0.3559236 , -0.32723973,  0.00540127]])

In [17]:
def hermitize(A):
    n, p = A.shape
    As = np.zeros(shape=(n+p, n+p))
    As[:n,n:] = A
    As[n:,:n] = A.T
    return As

In [16]:
Api = la.pinv(As)
np.where(np.abs(Api) < 1e-6, 0, Api)

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        , -0.25598533,  0.04935921, -0.14501155],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.03824366,  0.34310073, -0.12274237],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        , -0.06819445,  0.16015002, -0.3559236 ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.07011201,  0.32968007, -0.32723973],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.18594547, -0.16893236,  0.00540127],
       [-0.25598533,  0.03824366, -0.06819445,  0.07011201,  0.18594547,  0.        ,  0.        ,  0.        ],
       [ 0.04935921,  0.34310073,  0.16015002,  0.32968007, -0.16893236,  0.        ,  0.        ,  0.        ],
       [-0.14501155, -0.12274237, -0.3559236 , -0.32723973,  0.00540127,  0.        ,  0.        ,  0.        ]])

In [19]:
Mmag = np.array(
    [[1, 1, 0, 0, 0, 1, 0, 0],     # baseline type 1 (4 rows)
     [0, 1, 1, 0, 0, 1, 0, 0],
     [0, 0, 1, 1, 0, 1, 0, 0],
     [0, 0, 0, 1, 1, 1, 0, 0],
     [1, 0, 1, 0, 0, 0, 1, 0],     # baseline type 2 (3 rows)
     [0, 1, 0, 1, 0, 0, 1, 0],
     [0, 0, 1, 0, 1, 0, 1, 0],
     [1, 0, 0, 1, 0, 0, 0, 1],     # baseline type 3 (1 row)
     [0, 1, 0, 0, 1, 0, 0, 1],
     [1, 0, 0, 0, 0, 0, 0, 0]])    # magnitude constriant

In [20]:
Mmag.T @ Mmag

array([[4, 1, 1, 1, 0, 1, 1, 1],
       [1, 4, 1, 1, 1, 2, 1, 1],
       [1, 1, 4, 1, 1, 2, 2, 0],
       [1, 1, 1, 4, 1, 2, 1, 1],
       [0, 1, 1, 1, 3, 1, 1, 1],
       [1, 2, 2, 2, 1, 4, 0, 0],
       [1, 1, 2, 1, 1, 0, 3, 0],
       [1, 1, 0, 1, 1, 0, 0, 2]])

In [21]:
hermitize(Mmag)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 0., 1., 